### ISSUE TITLE
Problems using gruf

### ISSUE THREAD

**Issue by terabyte** [larsks/gruf#1]
Hey, cool looking tool.  Having some trouble using it though:

```
git clone git@github.com:larsks/gruf.git ~/projects/gruf
virtualenv ~/ves/gruf
sudo apt-get install python2.7-dev
~/ves/bin/pip install ~/projects/gruf
ln -s /home/cmyers/ves/gruf/bin/gruf ~/bin/gruf
```

Gruf now "works":
```
 16:23:12 ⮀ ὐB 100%  cmyers@powerhouse ⮀ @master ⮀ which gruf
/home/cmyers/bin/gruf
 16:23:15 ⮀ ὐB 100%  cmyers@powerhouse ⮀ @master ⮀ gruf --help
usage: gruf [-h] [--verbose] [--debug] [--remote REMOTE] [--config CONFIG]
            [--template TEMPLATE] [--inline-template INLINE_TEMPLATE]
            [--template-dir TEMPLATE_DIR] [--cache-lifetime CACHE_LIFETIME]
            [--filter FILTER]
            ...

positional arguments:
  cmd

optional arguments:
  -h, --help            show this help message and exit
  --verbose, -v
  --debug, -d
  --remote REMOTE, -r REMOTE
  --config CONFIG, -f CONFIG
  --template TEMPLATE, -t TEMPLATE
  --inline-template INLINE_TEMPLATE, -T INLINE_TEMPLATE
  --template-dir TEMPLATE_DIR
  --cache-lifetime CACHE_LIFETIME, -L CACHE_LIFETIME
  --filter FILTER, -F FILTER
```

Unfortunately, it doesn't "work work":

```
 16:23:45 ⮀ ὐB 100%  cmyers@powerhouse ⮀ @cmyers/fix-mon ⍟1 ⮀ pwd
/home/cmyers/projects/Kitchen-tools
 16:23:52 ⮀ ὐB 100%  cmyers@powerhouse ⮀ @cmyers/fix-mon ⍟1 ⮀ cat .git/config | grep gerrit
[remote "gerrit"]
        url = gerrit:Kitchen/tools
        fetch = +refs/heads/*:refs/remotes/gerrit/*
 16:24:00 ⮀ ὐB 100%  cmyers@powerhouse ⮀ @cmyers/fix-mon ⍟1 ⮀ gruf query open here
Traceback (most recent call last):
  File "/home/cmyers/bin/gruf", line 11, in <module>
    load_entry_point('gruf==0.3', 'console_scripts', 'gruf')()
  File "/home/cmyers/ves/gruf/local/lib/python2.7/site-packages/gruf/main.py", line 96, in main
    cache_lifetime=cache_lifetime)
  File "/home/cmyers/ves/gruf/local/lib/python2.7/site-packages/gruf/gerrit.py", line 84, in __init__
    git.get_remote_info(remote)))
TypeError: zip argument #2 must support iteration
```

I tried with python3, but that failed even harder unable to satisfy the urlopen dependency, so I assume python 2.7 is "correct"?

**Comment by larsks** [comment]
Gruf isn't able to parse your gerrit remote correctly. It's expecting an `ssh://` remote URL, as in:

    ssh://larsks@review.gerrithub.io:29418/larsks/gruf.git

It needs this in order to extract the appropriate host and port, etc.

**Comment by terabyte** [comment]
Thanks, that definitely fixed the problem!  looking now at the code, I'm a bit surprised it didn't give me a better error msg...

```
 21 def parse_gerrit_remote(url):
 22     if not url.startswith('ssh://'):
 23         raise ValueError('This code only works with ssh:// repository urls')
 24     parsed = urlparse.urlparse(url)
```

I didn't get a chance yet to see why this exception wasn't hit...but I do recommend at least a doc update which I will push shortly.
